import type { KeyDefinition } from './keyboard'

export const KEYCODES: KeyDefinition[] = [
  { code: 0x00, label: '禁用', category: 'special' },
  ...'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((label, index) => ({ code: 0x04 + index, label, category: 'basic' as const })),
  ...['1','2','3','4','5','6','7','8','9','0'].map((label, index) => ({ code: 0x1e + index, label, category: 'basic' as const })),
  { code: 0x28, label: 'Enter', category: 'basic' },
  { code: 0x29, label: 'Esc', category: 'basic' },
  { code: 0x2a, label: 'Backspace', category: 'basic' },
  { code: 0x2b, label: 'Tab', category: 'basic' },
  { code: 0x2c, label: 'Space', category: 'basic' },
  { code: 0x2d, label: '-', category: 'basic' },
  { code: 0x2e, label: '=', category: 'basic' },
  { code: 0x2f, label: '[', category: 'basic' },
  { code: 0x30, label: ']', category: 'basic' },
  { code: 0x31, label: '\\', category: 'basic' },
  { code: 0x33, label: ';', category: 'basic' },
  { code: 0x34, label: "'", category: 'basic' },
  { code: 0x35, label: '`', category: 'basic' },
  { code: 0x36, label: ',', category: 'basic' },
  { code: 0x37, label: '.', category: 'basic' },
  { code: 0x38, label: '/', category: 'basic' },
  { code: 0x39, label: 'Caps', category: 'modifier' },
  ...Array.from({ length: 12 }, (_, index) => ({ code: 0x3a + index, label: `F${index + 1}`, category: 'function' as const })),
  { code: 0x49, label: 'Insert', category: 'navigation' },
  { code: 0x4a, label: 'Home', category: 'navigation' },
  { code: 0x4b, label: 'Page Up', category: 'navigation' },
  { code: 0x4c, label: 'Delete', category: 'navigation' },
  { code: 0x4d, label: 'End', category: 'navigation' },
  { code: 0x4e, label: 'Page Down', category: 'navigation' },
  { code: 0x4f, label: '→', category: 'navigation' },
  { code: 0x50, label: '←', category: 'navigation' },
  { code: 0x51, label: '↓', category: 'navigation' },
  { code: 0x52, label: '↑', category: 'navigation' },
  { code: 0xe0, label: 'Left Ctrl', category: 'modifier' },
  { code: 0xe1, label: 'Left Shift', category: 'modifier' },
  { code: 0xe2, label: 'Left Alt', category: 'modifier' },
  { code: 0xe3, label: 'Left Win', category: 'modifier' },
  { code: 0xe4, label: 'Right Ctrl', category: 'modifier' },
  { code: 0xe5, label: 'Right Shift', category: 'modifier' },
  { code: 0xe6, label: 'Right Alt', category: 'modifier' },
  { code: 0xe7, label: 'Right Win', category: 'modifier' },
]

export const keyDefinition = (code: number): KeyDefinition =>
  KEYCODES.find((key) => key.code === code) ?? { code, label: `0x${code.toString(16).padStart(4, '0').toUpperCase()}`, category: 'special' }
