import { describe, expect, it, vi } from 'vitest'
import type { DeviceTransport } from '@/application/ports'
import { decodePacket, encodePacket } from '@/protocol/codec'
import { FirmwareChannel } from '@/protocol/xsyd/FirmwareChannel'
import { updateFirmware } from '@/protocol/xsyd/FirmwareUpdater'
import { firmwareCrc, firmwareSignature } from '@/protocol/xsyd/firmwareSignature'
import { validateC98Firmware } from '@/devices/c98/firmware'
import { XsydKeyboardProtocol } from '@/protocol/KeyboardProtocol'
import { HID_KEY_CATALOG } from '@/domain/keycodes'
import { StaticCapabilityDescriptor } from '@/domain/capabilities'

class BootDevice implements DeviceTransport {
  connected = true; productName = 'Test'; vendorId = 1; productId = 2
  mode = 0; capacity = 4096; board = 1
  reports = new Set<(data: Uint8Array) => void>()
  disconnects = new Set<() => void>()
  commands: { command: number; data: Uint8Array }[] = []
  memory = new Uint8Array(4096).fill(255)
  fragments: number[] = []
  wrongAddress = false; wrongCrc = false; rejectSign = false; incompleteErase = false
  async requestDevice() {} async reconnectAuthorized() { return true } async open() {} async close() {}
  onReport(listener: (data: Uint8Array) => void) { this.reports.add(listener); return () => { this.reports.delete(listener) } }
  onDisconnect(listener: () => void) { this.disconnects.add(listener); return () => { this.disconnects.delete(listener) } }
  respond(command: number, data: Uint8Array) { const packet = encodePacket(command | 128, data); this.reports.forEach((listener) => listener(packet)) }
  async send(frame: Uint8Array) {
    this.fragments.push(...frame)
    const length = this.fragments[1]! + 4
    if (this.fragments.length < length) return
    const { command, data } = decodePacket(Uint8Array.from(this.fragments.slice(0, length)))
    this.fragments = []
    this.commands.push({ command, data })
    const view = new DataView(data.buffer, data.byteOffset, data.byteLength)
    if (command === 1) {
      const reply = new Uint8Array(60); const v = new DataView(reply.buffer)
      v.setUint32(1, this.board, true); v.setUint16(5, this.capacity / 256, true)
      reply[7] = this.mode; reply[8] = 16; reply.set(Array.from({ length: 16 }, (_, i) => i), 9)
      this.respond(command, reply)
    } else if (command === 8) {
      this.respond(command, Uint8Array.of(this.rejectSign ? 1 : 0, data[0]!, 16, ...Array.from({ length: 16 }, (_, i) => i + 16)))
    } else if (command === 9) {
      this.respond(command, Uint8Array.of(0, 0))
      if (!this.incompleteErase) this.respond(command, Uint8Array.of(0, 255))
    } else if (command === 10) { this.mode = 255 }
    else if (command === 12) {
      const address = view.getUint32(0, true), size = view.getUint16(4, true)
      this.memory.set(data.slice(6, 6 + size), address)
      const reply = new Uint8Array(7); const v = new DataView(reply.buffer)
      v.setUint32(1, this.wrongAddress ? address + 1 : address, true); v.setUint16(5, size, true)
      this.respond(command, reply)
    } else if (command === 14) {
      const size = view.getUint32(4, true)
      const reply = new Uint8Array(11); const v = new DataView(reply.buffer)
      v.setUint32(5, size, true); v.setUint16(9, firmwareCrc(this.memory.slice(0, size)) ^ (this.wrongCrc ? 1 : 0), true)
      this.respond(command, reply)
    } else if (command === 11) { this.mode = 0 }
  }
}

const perform = (device: BootDevice, reconnect = vi.fn(async () => new FirmwareChannel(device))) => {
  const onProgress = vi.fn()
  const promise = updateFirmware(new FirmwareChannel(device), new Uint8Array(600).fill(42), { onProgress, authorizeDevice: vi.fn() }, reconnect, async () => {})
  return { promise, onProgress, reconnect }
}

describe('official firmware protocol', () => {
  it('opens a boot-only recovery profile without sending application configuration commands', async () => {
    const device = new BootDevice(); device.mode = 255
    const protocol = new XsydKeyboardProtocol(device, HID_KEY_CATALOG, new StaticCapabilityDescriptor('test', {
      layers: 1, remap: true, restoreFactory: true, layoutRows: 1, layoutColumns: 1,
    }), () => [])
    try {
      const profile = await protocol.getProfile()
      expect(profile.device.runMode).toBe('boot')
      expect(profile.capabilities.remap).toBe(false)
      expect(device.commands.map(({ command }) => command)).toEqual([1])
    } finally { protocol.close() }
  })
  it('matches signature vectors evaluated from official SDK 1.0.24, not generated by this implementation', () => {
    const vectors = [
      [175,125,42,122,172,85,249,245,225,251,213,30,163,180,64,210],
      [227,169,43,82,182,230,207,64,35,220,129,44,16,172,206,80],
      [150,35,130,231,105,76,202,232,104,160,212,48,97,21,189,63],
      [74,136,64,80,13,174,232,211,182,38,184,244,237,158,246,145],
      [224,8,120,23,34,205,82,190,204,174,83,172,151,206,144,158],
    ]
    vectors.forEach((vector, i) => expect(firmwareSignature(Uint8Array.from({ length: 16 }, (_, n) => n), i + 2)).toEqual(vector))
    expect(firmwareCrc(new TextEncoder().encode('123456789'))).toBe(8585)
  })

  it('pads to 512, sends four HID reports per 244-byte chunk, verifies CRC and reconnects to app', async () => {
    const device = new BootDevice()
    const { promise, onProgress, reconnect } = perform(device)
    await promise
    const writes = device.commands.filter(({ command }) => command === 12)
    expect(writes).toHaveLength(5)
    expect(writes.map(({ data }) => new DataView(data.buffer).getUint16(4, true))).toEqual([244,244,244,244,48])
    expect([...device.memory.slice(600, 1024)]).toEqual(Array(424).fill(255))
    expect(device.commands.filter(({ command }) => command === 10)).toHaveLength(1)
    expect(reconnect).toHaveBeenCalledTimes(2)
    expect(onProgress.mock.lastCall![0].stage).toBe('complete')
    expect(device.reports.size).toBe(0)
  })

  it('resumes from Bootloader without repeating the app-to-boot erase/reboot', async () => {
    const device = new BootDevice(); device.mode = 255
    await perform(device).promise
    expect(device.commands.some(({ command }) => command === 10)).toBe(false)
    expect(device.commands.filter(({ command }) => command === 9)).toHaveLength(1)
  })

  it.each(['wrongAddress', 'wrongCrc', 'rejectSign'] as const)('stops on %s without jumping to app or retrying a write', async (fault) => {
    const device = new BootDevice(); device[fault] = true
    await expect(perform(device).promise).rejects.toThrow()
    expect(device.commands.some(({ command }) => command === 11)).toBe(false)
    if (fault === 'wrongAddress') expect(device.commands.filter(({ command }) => command === 12)).toHaveLength(1)
    expect(device.reports.size).toBe(0)
  })

  it('rejects over-capacity images before any erase or unlock', async () => {
    const device = new BootDevice(); device.capacity = 512
    await expect(perform(device).promise).rejects.toThrow('空间')
    expect(device.commands.map(({ command }) => command)).toEqual([1])
  })

  it('rejects a different board after reboot before writing firmware', async () => {
    const device = new BootDevice()
    const reconnect = vi.fn(async () => { device.board = 2; return new FirmwareChannel(device) })
    await expect(perform(device, reconnect).promise).rejects.toThrow('板卡')
    expect(device.commands.some(({ command }) => command === 12)).toBe(false)
  })

  it('waits for erase completion and times out without advancing to writes', async () => {
    vi.useFakeTimers()
    try {
      const device = new BootDevice(); device.incompleteErase = true
      const check = expect(perform(device).promise).rejects.toThrow('超时')
      await vi.runAllTimersAsync(); await check
      expect(device.commands.some(({ command }) => command === 12)).toBe(false)
      expect(device.reports.size).toBe(0)
    } finally { vi.useRealTimers() }
  })

  it('rejects arbitrary bin files, including a same-size modified image', async () => {
    await expect(validateC98Firmware(new Uint8Array(1))).rejects.toThrow('105588')
    await expect(validateC98Firmware(new Uint8Array(105588))).rejects.toThrow('SHA-256')
  })
})
