const messages = {
  tlw: {
    fireKey: '火力键',
    shortcutKey: '快捷键',
    fireCount: '连点次数',
    fireInterval: '连点间隔（毫秒）',
    fireMacroHint: '使用设备共用宏槽，已有宏按键也会改为执行此连点内容。',
    wireless: '2.4G 无线连接',
    clearAndSaveMacro: '清空并保存宏',
    macroTextHint:
      '编辑 JSON 动作数组：delay 是动作后延时（0–65535 ms），typeAndStatus 为键盘按下/抬起 138/10、鼠标按下/抬起 129/1，code 为按键代码。',
    resetAllKeys: '重置所有按键',
    playbackMode: '播放模式',
    playbackCount: '播放次数',
    playNormal: '正常播放',
    playRelease: '释放停止',
    playTrigger: '触发停止',
    playReleaseImmediately: '释放立即停止',
    playReleaseHint: '松开按键后，播放完当前一轮宏再停止。',
    playTriggerHint: '播放宏时，再次按下该按键停止播放。',
    playReleaseImmediatelyHint: '松开按键后立即停止播放宏。',
    operationCompleted: '{operation}已完成',
    basicKeys: '基本按键',
    mouseKeys: '鼠标按键',
    mediaOffice: '多媒体 / 办公',
    defaultProfile: '默认配置',
    defaultMacro: '默认宏',
    enabled: '启用',
    keepDpi: '请至少保留一个启用的 DPI 档位。',
    unsupportedReportRate: '回报率超出当前鼠标支持范围。',
    unsupportedLightMode: '灯效模式超出当前鼠标支持范围。',
    unsupportedBrightness: '亮度超出当前鼠标支持范围。',
    unsupportedLightSpeed: '灯效速度超出当前鼠标支持范围。',
    unsupportedProfileValue: '配置中的数值超出当前鼠标支持范围。',
    disabledDpi: '配置选择了已关闭的 DPI 档位。',
    flow: '流光',
    neon: '霓虹',
    chase: '跑马',
    colorBreathing: '混彩呼吸',
    off: '全灭',
    lightSpeed: '速度',
    lightingSettings: '灯效设置',
    macroEditor: '宏编辑',
    actionList: '动作列表',
    profiles: '配置文件',
    profile: '配置',
    profileHint: '保存当前设置；点击配置下发到鼠标。修改设置后，可覆盖保存。',
    actions: '操作',
    newProfile: '新建配置',
    rename: '重命名',
    overwrite: '覆盖为当前设置',
    export: '导出',
    import: '导入',
    delete: '删除',
    name: '名称',
    save: '保存',
    fileError: '文件格式不正确或本地存储失败。',
    profileMissingMacro:
      '无法保存配置。请检查名称；若按键已绑定宏，请先在宏页面重新绑定，以包含完整宏数据。',
    macros: '宏',
    newMacro: '新建宏',
    macroHint:
      '宏保存在本地。绑定时写入设备宏 0，已有宏按键会一同使用新宏。延时表示该动作之后等待的毫秒数。',
    macroError: '请检查宏名称和动作，延时范围为 0–65535 ms。',
    record: '开始录制',
    stopRecording: '停止录制',
    recording: '正在录制键盘输入，点击停止录制结束。',
    addAction: '添加动作',
    clear: '清空',
    action: '动作',
    down: '按下',
    up: '抬起',
    delay: '动作后延时',
    moveUp: '上移',
    moveDown: '下移',
    saveMacro: '保存宏',
    insertDelayHint:
      '在所选位置增加等待时间，显示在前一动作的延迟中；首个动作之前不能插入，累计上限为 65535 ms。',
    bindMacro: '宏绑定的按键',
    macroSaved: '宏数据已发送，按键和设置已回读确认；请按键验证宏效果。',
    connected: '已连接',
    refresh: '刷新',
    disconnect: '断开连接',
    working: '正在与鼠标同步…',
    saved: '已保存并回读确认',
    failed: '操作未完成，请刷新检查当前设置。若持续失败，请断开后重新连接。',
    keepLeft: '请至少保留一个鼠标左键。',
    dpi: 'DPI 灵敏度',
    step: '步进',
    current: '当前',
    sensitivity: '灵敏度',
    apply: '应用',
    performance: 'DPI设置',
    rate: '回报率',
    existing: '保留当前功能',
    lighting: '灯光设置',
    mode: '灯效模式',
    steady: '常亮',
    breathing: '呼吸',
    brightness: '亮度',
    dim: '较暗',
    bright: '较亮',
    color: '颜色',
    keys: '按键设置',
    keysHint: '点击鼠标按键，选择要分配的功能',
    mouse: '鼠标功能',
    keyboard: '键盘按键',
    resetKey: '恢复该键默认功能',
    key: '按键',
    device: '设备',
    currentConfig: '当前配置',
    start: '开始设置',
    usb: '有线连接',
    settings: '设备设置',
    sync: '从鼠标读取最新配置',
    mouse0: '左键',
    mouse1: '右键',
    mouse2: '中键',
    mouse3: '后退',
    mouse4: '前进',
    mouse5: 'DPI 增加',
    mouse6: 'DPI 减少',
    clearLocalConfirm: '清除本机的 {model} 配置文件和宏？其他设备的数据不会被删除。',
    localCleared: '已清除本地数据并创建默认项。',
  },
  set: {
    title: '设置',
    lang: '语言',
    mode_title: '按键去抖',
    mode_game: '游戏模式',
    mode_work: '办公模式',
    keyboard_info: '键盘信息',
    keyboard_name: '键盘名称：',
    keyboard_sn: '键盘序列号：',
    keyboard_version: '固件版本：',
    keyboard_mode: '运行模式：',
    latest: '最新版本：',
    into_boot: '进入升级模式',
    layer_1: '启用Tape层',
    but_1: '清除本地数据',
    but_2: '恢复出厂设置',
    but_3: '驱动更新',
    but_4: '固件更新',
    but_5: '是',
    but_6: '否',
    local_fw: '固件下载更新',
    online_fw: '固件在线更新',
    but_7: '接收器更新',
    but_8: '进入升级模式',
    but_9: '重启',
    but_10: '选择文件',
    but_11: '升级',
    title_1: '恢复出厂设置将清除所有数据，是否继续？',
    title_2: '无需更新',
    title_3: '更新版本',
    title_4: '下载中',
    title_5: '请到有线模式下更新',
    title_6: '功能设置',
    title_7: '将清除本地所有数据,是否继续?',
    title_8: '进入升级模式将会擦除键盘当前固件并重新连接，是否继续？',
    title_9: '此操作执行后键盘程序将被清除！不升级固件将无法使用！是否确认继续擦除？',
    title_10: '设备重启后将进入升级模式，请重新连接设备进行升级。',
    title_11: '选择一个bin文件并点击升级按钮！',
    title_12: '固件下载成功，点击确定进入APP模式！',
    title_13: '固件升级成功！',
    title_14: '手动选择电脑中的bin文件进行升级！',
    title_15: '时刻保持最新版本固件，以获得键盘最佳的使用体验！',
    title_16: '下载固件失败，请与网站管理员联系！',
    title_17: '固件升级失败: CRC校验失败！',
    title_18: '这不是Edge60 PlayerEdition的固件,请选择正确的固件！',
    title_19: '这不是Edge60 探索版的固件,请选择正确的固件！',
    title_20: '时刻保持最新版本固件，以获得设备最佳的使用体验！',
    fw_current: '当前版本',
    fw_latest_ok: '已是最新版本固件',
    fw_has_update: '发现新版本固件',
    fw_update_time: '更新时间',
    fw_steps: '请按照以下步骤操作',
    fw_warning: '* 刷入固件过程中，不要让设备与电脑断联。',
    fw_wire_tip: '请在有线模式下进行固件升级',
    fw_next: '下一步',
    offline: '本地更新',
    online: '在线更新',
    tocuh_pad: '开启触摸面板',
    tocuh_pad_mac: 'MAC系统下使用网址功能需手动打开浏览器新建空白页',
    confirm: '确定',
    cancel: '取消',
    set_website: '网址',
    website_input_tip: '点击输入自定义网址',
    driver_1: '软件驱动App下载',
    driver_2: '可用驱动',
    driver_3: '驱动暂不可用',
    driver_4: '正在下载...',
    driver_5: '下载已开始',
    driver_6: '下载失败，请重试',
    driver_7: '选择连接模式',
    driver_8: '产品名称',
    driver_9: '连接模式',
    driver_10: '取消',
    driver_11: '下载',
    driver_12: '单模低延迟',
    driver_13: '三模低延迟',
    driver_14: '三模',
    driver_15: '单模',
  },
  macro: {
    title: '宏列表',
    title_1: '宏设置',
    title_2: '宏记录',
    title_3: '插入事件',
    title_4: '重复次数',
    title_5: '请先停止宏录制',
    title_6: '宏文件保存完成',
    title_7: '重复间隔（毫秒）',
    title_8: '按住循环（松开停止）',
    title_9: '循环至任意键按下',
    title_10: '循环至触发键再按',
    title_11: '循环指定次数',
    title_12: '当前宏有未保存的修改，请点击保存',
    but_1: '新建',
    but_2: '导入',
    but_3: '插入',
    but_4: '开始录制',
    but_5: '清空',
    but_6: '刪除',
    but_7: '保存',
    but_8: '停止录制',
    but_9: '编辑',
    but_10: '删除',
    but_11: '导出',
    but_12: '文本',
    menu_1: '键盘',
    menu_2: '延迟',
    menu_3: '鼠标',
    menu_4: '记录延迟',
    menu_5: '默认延迟',
    menu_6: '固定延迟',
    event_1: '在这之前插入事件',
    event_2: '在这之后插入事件',
    desc_1:
      '宏对象以JSON的格式进行编辑，一个宏由多个动作（Action）数组组成。每个Action是一个JSON格式的对象，其包含以下对象：',
    desc_2: 'action：动作类型 1:弹起 0:按下',
    desc_3: 'type：按键类型 0:普通按键',
    desc_4: 'delay：延迟时间 单位:毫秒',
    desc_5: 'key：按键HID键值',
    desc_6: 'index：动作顺序',
    desc_7: '宏动作已达上限！',
    desc_8: '宏数量已达上限！',
    mouse_btn_left: '鼠标左键',
    mouse_btn_right: '鼠标右键',
    mouse_btn_mid: '鼠标中键',
    mouse_btn_back: '鼠标后退',
    mouse_btn_forward: '鼠标前进',
    mouse_btn_wheel_up: '滚轮上',
    mouse_btn_wheel_down: '滚轮下',
  },
  home: {
    title: '浏览器不支持WebHID或WebHID不可用',
    title_1: '请稍等，正在同步数据 。。。',
    title_2: '欢迎来到 RK HUB WEB',
    title_3: '支持有线连接及 2.4G 无线接收器两种连接方式',
    title_4: '当前兼容 Chrome、Edge、Opera 浏览器，更多浏览器适配开发进行中。',
    title_6: '官网：',
    title_7: '微信扫一扫 加我为好友',
    title_tip: '进入产品驱动。',
    but_1: '连接',
    but_2: '选择其他设备',
    but_3: '点击进入',
    but_4: '关闭设备',
    but_5: '选择设备',
    profile:
      '您本地存储的配置文件已经过期，推荐您重置所有配置数据，如果不重置，可能会出现意想不到的问题。',
    profile_out: '配置文件已经过期',
    profile_reset: '重置',
    profile_goon: '继续',
    device_not_supported: '不支持的设备',
    menu: '主页',
    menu_1: '按键设置',
    menu_2: '宏管理器',
    menu_3: 'DPI设置',
    menu_4: '性能设置',
    menu_5: '设置',
    menu_6: '键盘设置',
    menu_7: '宏管理器',
    menu_8: '灯光模式',
    menu_9: '功能设置',
    menu_10: 'TFT设置',
    menu_11: '固件更新',
    title_00: '全自研驱动',
    title_01: '下载APP客户端',
    title_02: '点击下载',
    title_03: '官方微信',
    title_04: 'RK官网',
    title_05: '点击直达',
    timeout: '加载数据超时',
    load_timeout: '请下载最新固件，重新拔插设备后升级到最新版本!',
  },
  mediaKey: {
    title: '多媒体按键',
    Media: '媒体',
    NextTr: '下一首',
    PrevTr: '上一首',
    Stop: '停止',
    Eject: '弹出',
    PlayPause: '播放/暂停',
    Mute: '静音',
    VolumI: '音量+',
    VolumD: '音量-',
    SysBkBrigthDec: '亮度-',
    SysBkBrigthInc: '亮度+',
    Player: '播放器',
    Mail: '邮件',
    Calculator: '计算器',
    Explorer: '资源管理器',
    Home: '主页',
    Search: '搜索',
    Forward: '前进',
    Back: '后退',
    StopWeb: '停止网页',
    Refresh: '刷新',
    Favorites: '收藏夹',
  },
}

export function mouseFailureMessage(cause: unknown): string {
  const message = cause instanceof Error ? cause.message : ''
  if (message.includes('left mouse button')) return mouseLabel('keepLeft')
  if (message.includes('Keep at least one DPI stage')) return mouseLabel('keepDpi')
  if (message.includes('Unsupported report rate')) return mouseLabel('unsupportedReportRate')
  if (message.includes('Unsupported light mode')) return mouseLabel('unsupportedLightMode')
  if (message.includes('Unsupported brightness')) return mouseLabel('unsupportedBrightness')
  if (message.includes('Unsupported light speed')) return mouseLabel('unsupportedLightSpeed')
  if (
    message.includes('DPI rank') ||
    message.includes('DPI stage enable') ||
    message.includes('independent XY') ||
    message.includes('empty key slot') ||
    message.includes('outside the device key matrix')
  )
    return mouseLabel('unsupportedProfileValue')
  if (message.includes('disabled DPI')) return mouseLabel('disabledDpi')
  return message || '操作失败，请重新连接设备'
}

export function mouseLabel(key: string, params: Record<string, string | number> = {}): string {
  const segments = (key.includes('.') ? key : 'tlw.' + key).split('.')
  let value: unknown = messages
  for (const part of segments)
    value =
      value && typeof value === 'object' ? (value as Record<string, unknown>)[part] : undefined
  let result = typeof value === 'string' ? value : key
  for (const [name, replacement] of Object.entries(params))
    result = result.replaceAll('{' + name + '}', String(replacement))
  return result
}
export const useMouseLabels = () => ({ t: mouseLabel })
