import '@fontsource/inter/400.css'
import '@fontsource/inter/500.css'
import '@fontsource/inter/600.css'
import './styles.css'
import './layout.css'
import './ui-overrides.css'
import './ui/settings.css'
import './ui/lighting.css'
import './ui/advanced-key.css'
import './ui/key-test.css'
import './ui/keyboard-scroll.css'
import './ui/global-responsive.css'
import { createApp } from 'vue'
import { createPinia } from 'pinia'
import App from './App.vue'

createApp(App).use(createPinia()).mount('#app')
